### ISSUE TITLE
README examples & Tools

### ISSUE THREAD

**Issue by casperlundberg** [PepperonIT/blockly-site#8]
**Look in the documentation standard before starting**
[Documentation standard](https://github.com/D7017E/Documentation/tree/main/Standard)

TODO:

- [x] Add some examples of how the app looks like, how it behaves and whats expected in the console when sending code to the server and then what's Pepper expected to do under _Examples_ in the README.
- [x] Add a short descriptions of the tools and frameworks used (already listed) in the README.
- [x] Create an MD-file with detailed description for every tool and framework explaining why and how it is used.
- [x] Add links to the tools and frameworks own detailed description and if there is no need to give additional information in the form of commands, flags, settings etc then just the tools and frameworks own API documentation may work for now. Aim for creating our own documentation as described in the bullet above this one.

**Comment by casperlundberg** [comment]
Redo all of ti with new information and remember to follow the code standard declared in the docs repo, link in description of this issue.

**Comment by noorbhtiti** [comment]
Isn't this done already? @casperlundberg
